/* A focused learning path; all other application topics remain accessible. */
const basicGroups={knots:{he:'10 קשרים שימושיים',en:'10 useful knots'},shelter:{he:'3 מחסות',en:'3 shelters'},fire:{he:'3 מיומנויות אש',en:'3 fire skills'},navigation:{he:'4 מיומנויות ניווט ואיתות',en:'4 navigation and signalling skills'}};
let basicPractised=[];try{const saved=JSON.parse(store.get('sg_basic_practised')||'[]');if(Array.isArray(saved))basicPractised=saved.filter(id=>Object.hasOwn(BASIC_GUIDES,id));}catch{}
function basicSource(step){return step.credit.includes('CC0')?'<a href="credits.html">rkdarst · CC0</a>':step.credit.includes('CC BY-SA')?'<a href="credits.html">Kyle Corry · Trail Sense · CC BY-SA 4.0</a>':vText('איור סכמטי חדש · המדריך לצופה','New schematic · Scout’s Guide');}
for(const [id,g] of Object.entries(BASIC_GUIDES)){
 const it=vTopic(id).it;
 // Preserve the previous wording for review and keep speech/search in sync with the displayed guide.
 g.previousSteps=it.steps;
 it.steps=g.steps.map(st=>({text:{he:st.title.he+'. '+st.text.he,en:st.title.en+'. '+st.text.en},svg:''}));
 if(!SCOUT_VISUALS[id])SCOUT_VISUALS[id]=[{src:g.cover,title:it.title,width:640,height:380,credit:'Scout’s Guide · New schematic',source:'credits.html',license:'credits.html'}];
}
vTopic('halfhitch').it.title.he='שני חצאי קביעה';
vTopic('sheetbend').it.title.he='קשר אורגים';
vTopic('overhandloop').it.title.he='לולאת בוהן';
vTopic('cowhitch').it.title.he='ראש עפרוני';
vTopic('pitchtent').it.lead={he:'הקמה מסודרת של אוהל כיפה, בהתאם לדגם ולתנאי המקום.',en:'A methodical dome-tent setup, adapted to its model and the site.'};
vTopic('compass').it.lead={he:'היכרות עם צפון מגנטי ועם חץ כיוון ההליכה במצפן פיזי.',en:'Recognizing magnetic north and the travel arrow on a physical compass.'};
vTopic('extinguish').it.tips=[{he:'הכינו מספיק מים לפני שמדליקים. כיסוי באדמה בלבד עלול להשאיר גחלים חמות מתחת לפני השטח.',en:'Have enough water before lighting. Covering with dirt alone can leave hot embers underneath.'}];
vTopic('leanto').it.tips=[{he:'זהו מחסה חד־צדדי. אל תבנו אש בתוך המחסה או סמוך לחומר הכיסוי.',en:'This is a one-sided shelter. Do not build a fire inside or close to its covering.'}];
vTopic('mirror').it.safety=[{he:'אין להביט בשמש. בעת תרגול אין לכוון הבזקים לעיני אנשים, לנהגים או למטוסים.',en:'Never look at the sun. During practice, do not direct flashes at people’s eyes, drivers or aircraft.'}];
const basicGuideFallback=visualGuide;
visualGuide=function(it){const g=BASIC_GUIDES[it.id];if(!g)return basicGuideFallback(it);
 return `<div class="basic-meta"><div><h3>${vText('מה צריך','What you need')}</h3><p>${vEscape(L(g.equipment))}</p></div><div><h3>${vText('מתי משתמשים','When to use it')}</h3><p>${vEscape(L(g.use))}</p></div></div><section class="basic-view"><header><h2>${vText('צעד אחר צעד','Step by step')}</h2><span>${g.steps.length} ${vText('שלבים','steps')}</span></header><div id="basic-frame-${it.id}"></div></section><div class="basic-review"><h3>${vText('טעות שכדאי להימנע ממנה','A mistake to avoid')}</h3><p>${vEscape(L(g.mistake))}</p></div><div class="basic-review check"><h3>${vText('איך בודקים את התוצאה','Check the result')}</h3><p>${vEscape(L(g.check))}</p></div><details class="basic-all"><summary>${vText('כל השלבים ברצף','All steps together')}</summary>${g.steps.map((st,i)=>`<article><img src="${st.image}" alt="${vEscape(L(st.title))}" loading="lazy"><h3>${i+1}. ${vEscape(L(st.title))}</h3><p>${vEscape(L(st.text))}</p><small>${basicSource(st)}</small></article>`).join('')}</details><div class="basic-practice"><button class="btn" id="basic-practice-${it.id}" aria-pressed="${basicPractised.includes(it.id)}" onclick="toggleBasicPractice('${it.id}')">${basicPractised.includes(it.id)?vText('✓ תרגלתי את ההדרכה','✓ I practised this guide'):vText('סימון: תרגלתי את ההדרכה','Mark: I practised this guide')}</button><button class="btn ghost" onclick="openBasics()">${vText('חזרה לחבילת הבסיס','Back to the essentials')}</button></div><p class="basic-small-note">${vText('הסימון הוא מעקב אישי אחר תרגול, ולא אישור מיומנות.','The mark tracks your practice; it does not certify proficiency.')}</p>`;
};
function renderBasicFrame(id,i=0){const g=BASIC_GUIDES[id];if(!g||i<0||i>=g.steps.length)return;const node=$('basic-frame-'+id);if(!node)return;const st=g.steps[i],previous=document.activeElement?.dataset?.basicControl;
 node.innerHTML=`<img class="basic-art" src="${st.image}" alt="${vEscape(L(st.title)+'. '+L(st.text))}"><div class="basic-copy" aria-live="polite"><h3>${i+1}. ${vEscape(L(st.title))}</h3><p>${vEscape(L(st.text))}</p></div><div class="basic-controls"><button class="btn ghost" data-basic-control="previous" ${i===0?'disabled':''} onclick="renderBasicFrame('${id}',${i-1})">${vText('הקודם','Previous')}</button><div class="basic-dots">${g.steps.map((_,j)=>`<button data-basic-control="step-${j}" aria-label="${vText('שלב','Step')} ${j+1}" aria-pressed="${i===j}" onclick="renderBasicFrame('${id}',${j})">${j+1}</button>`).join('')}</div><button class="btn" data-basic-control="next" ${i===g.steps.length-1?'disabled':''} onclick="renderBasicFrame('${id}',${i+1})">${vText('הבא','Next')}</button></div><div class="basic-source">${basicSource(st)}</div>`;
 if(previous){const target=node.querySelector(`[data-basic-control="${previous}"]:not(:disabled)`)||node.querySelector(`[data-basic-control="step-${i}"]`);target?.focus({preventScroll:true});}
}
const openItemBeforeBasics=openItem;openItem=function(key,id){openItemBeforeBasics(key,id);if(BASIC_GUIDES[id]&&currentItem===id&&$('detail').classList.contains('active'))renderBasicFrame(id);};
function openBasics(){
 $('basicsBody').innerHTML=`<div class="visual-eyebrow">${vText('מתחילים כאן','START HERE')}</div><h1>${vText('20 מיומנויות לשטח','20 field essentials')}</h1><p class="hint">${vText('בוחרים הדרכה, מכינים את הציוד ועוברים שלב אחר שלב. אפשר לחזור ולתרגל בכל זמן.','Choose a guide, gather your equipment and follow each step. Return and practise any time.')}</p><div class="basic-overview"><span>${vText('התרגול שלי','My practice')}</span><strong>${basicPractised.length} / 20</strong></div><progress class="basic-progress" value="${basicPractised.length}" max="20" aria-label="${vText('הדרכות שתרגלתי','Guides practised')}"></progress>${Object.entries(basicGroups).map(([group,title])=>`<section class="basic-chapter"><h2>${L(title)}</h2><div class="basic-grid">${Object.entries(BASIC_GUIDES).filter(([,g])=>g.group===group).map(([id,g])=>{const {key,it}=vTopic(id),locked=it.kidsLock&&S.age==='kids';return `<button class="basic-card" onclick="openItem('${key}','${id}')"><img src="${g.cover}" alt="${vEscape(L(it.title))}" loading="lazy">${basicPractised.includes(id)?`<span class="basic-done">${vText('✓ תרגלתי','✓ Practised')}</span>`:''}<b>${vEscape(L(it.title))}</b><small>${g.steps.length} ${vText('שלבים מאוירים','illustrated steps')}${locked?' · '+vText('בליווי מבוגר','Adult supervision'):''}</small></button>`;}).join('')}</div></section>`).join('')}`;go('basics');
}
function toggleBasicPractice(id){if(basicPractised.includes(id))basicPractised=basicPractised.filter(x=>x!==id);else basicPractised.push(id);store.set('sg_basic_practised',JSON.stringify(basicPractised));const b=$('basic-practice-'+id);if(b){b.setAttribute('aria-pressed',basicPractised.includes(id));b.textContent=basicPractised.includes(id)?vText('✓ תרגלתי את ההדרכה','✓ I practised this guide'):vText('סימון: תרגלתי את ההדרכה','Mark: I practised this guide');}}
const renderHomeBeforeBasics=renderHome;renderHome=function(){renderHomeBeforeBasics();$('visualFeatured').insertAdjacentHTML('afterbegin',`<section class="basic-entry"><span class="visual-eyebrow">${vText('מתחילים כאן','START HERE')}</span><h2>${vText('הבסיס ליציאה לשטח','Your field essentials')}</h2><p>${vText('20 הדרכות עם ציוד, שלבים מאוירים ובדיקת התוצאה.','20 guides with equipment, illustrated steps and a final check.')}</p><div class="basic-entry-art">${['bowline','tarp','build','compass'].map(id=>`<img src="${BASIC_GUIDES[id].cover}" alt="${vEscape(L(vTopic(id).it.title))}">`).join('')}</div><button class="btn" onclick="openBasics()">${vText('לפתיחת חבילת הבסיס ←','Open the essentials →')}</button></section>`);};
const backBeforeBasics=goBackList;goBackList=function(){if(detailOrigin==='basics')openBasics();else backBeforeBasics();};
document.addEventListener('DOMContentLoaded',()=>{const s=document.createElement('section');s.id='basics';s.className='screen';s.innerHTML=`<button class="backbtn" onclick="go('home')">${vText('→ חזרה לבית','← Back home')}</button><div id="basicsBody"></div>`;$('home').parentElement.appendChild(s);});
