/* Educational revision; not clinical certification. */
const PRO_SOURCES={
knots:{name:'rkdarst — Knot reference',url:'https://github.com/rkdarst/knots'},
hike:{name:'NPS — Hiking safety',url:'https://www.nps.gov/subjects/trails/hiking-safety.htm'},
packing:{name:'REI — Packing a backpack',url:'https://www.rei.com/learn/expert-advice/loading-backpack.html'},
fire:{name:'NPS — Fire safety',url:'https://www.nps.gov/brca/learn/nature/fire-safety.htm'},
cpr:{name:'Red Cross — Hands-only CPR',url:'https://www.redcross.org/take-a-class/cpr/performing-cpr/hands-only-cpr'},
aed:{name:'Red Cross — AED steps',url:'https://www.redcross.org/take-a-class/aed/using-an-aed/aed-steps'},
choking:{name:'Red Cross — Choking',url:'https://www.redcross.org/take-a-class/resources/learn-first-aid/adult-child-choking'},
burn:{name:'NHS — Burns and scalds',url:'https://www.nhs.uk/conditions/burns-and-scalds/'},
heat:{name:'NHS — Heat illness',url:'https://www.nhs.uk/conditions/heat-exhaustion-heatstroke/'},
snake:{name:'מד״א — הכשת נחש',url:'https://www.mdais.org/101/snake-bite'},
cold:{name:'NHS — Hypothermia',url:'https://www.nhs.uk/conditions/hypothermia/'},
bites:{name:'NHS — Bites and stings',url:'https://www.nhs.uk/conditions/insect-bites-and-stings/'},
animal:{name:'NHS — Animal bites',url:'https://www.nhs.uk/conditions/animal-and-human-bites/'},
eye:{name:'NHS — Eye injuries',url:'https://www.nhs.uk/conditions/eye-injuries/'},
seizure:{name:'NHS — Seizure first aid',url:'https://www.nhs.uk/symptoms/what-to-do-if-someone-has-a-seizure-fit/'},
chemical:{name:'NHS — Chemical burns',url:'https://www.nhs.uk/conditions/acid-and-chemical-burns/'},
head:{name:'NHS — Head injury',url:'https://www.nhs.uk/conditions/head-injury-and-concussion/'},
aid:{name:'St John Ambulance — First aid reference',url:'https://www.sja.org.uk/first-aid-advice/'}};
function proMedical(id,title,why,warning,steps,en,source,mistake){
 const it=CONTENT.firstaid.items.find(x=>x.id===id);if(!it)throw Error('Unknown topic '+id);
 it.title.he=title;it.lead={he:why,en:'Educational first-aid overview. Seek appropriate medical help and follow emergency dispatch instructions.'};
 it.safety=[{he:warning,en:'For serious or worsening symptoms call local emergency services (101 in Israel). Follow dispatch instructions. This overview does not replace practical training.'}];
 const eng=en.split('~');it.steps=steps.split('~').map((t,i)=>({text:{he:t,en:eng[i]},svg:''}));it.tips=[];it.kidsLock=false;
 PRO_GUIDES[id]={why,equipment:'טלפון, אמצעי הגנה וערכת עזרה ראשונה בהתאם להכשרה. אין לעכב הזעקת עזרה כדי לאסוף ציוד.',mistake,check:'עוקבים אחר ההכרה והנשימה ומוסרים לצוות מתי התחיל האירוע, מה השתנה ומה נעשה.',sources:source.split(',')};
}
proMedical('cpr','החייאה במבוגר ו־AED','במבוגר שאינו מגיב ואינו נושם כרגיל, מתחילים עזרה מיד. נשימות בודדות ומתנשפות אינן נשימה תקינה. לילד, תינוק או טביעה נדרשות הנחיות מתאימות מהמוקד ומההכשרה.','חייגו 101 בישראל והפעילו רמקול. בקשו להביא AED בלי לעכב התחלת החייאה.',
'ודאו שהמקום בטוח. בדקו תגובה בקריאה ובנגיעה בכתפיים. אם אין תגובה, בדקו נשימה תקינה עד 10 שניות.~בהיעדר נשימה תקינה, הניחו על הגב על משטח קשיח. הניחו עקב כף יד במרכז החזה ויד שנייה מעליה.~לחצו בזרועות ישרות 100–120 פעמים בדקה, לעומק 5–6 ס״מ במבוגר. אפשרו חזרה מלאה וצמצמו הפסקות. מי שהוכשר ומסוגל נותן הנשמות לפי הכשרתו; אחרת ממשיכים בלחיצות ובהנחיית המוקד.~כשה־AED מגיע, הפעילו והדביקו את המדבקות לפי הציור. אין לגעת בנפגע בזמן ניתוח קצב או שוק. חזרו מיד להחייאה לפי המכשיר.~המשיכו עד שהצוות מחליף אתכם, שחוזרים סימני חיים ונשימה תקינה או שאינכם יכולים להמשיך. דווחו למוקד על שינוי.',
'Check scene safety, response and normal breathing for no more than 10 seconds.~If not breathing normally, put the adult on their back on a firm surface, with one hand in the centre of the chest and the other on top.~Give 100–120 compressions per minute, 5–6 cm deep, with full recoil and minimal pauses. Give breaths if trained and able, otherwise continue compressions and dispatcher guidance.~Turn on the AED and follow pad diagrams and prompts. Nobody touches during analysis or shock. Immediately resume CPR as prompted.~Continue until professionals take over, normal breathing and signs of life return, or you cannot continue. Report changes.',
'cpr,aed','להפסיק כשהמכשיר מגיע במקום להפעילו, או לפרש התנשפות כנשימה תקינה.');
proMedical('choking','חנק במבוגר ובילד מעל שנה','מבדילים בין שיעול יעיל לבין חסימה קשה שאינה מאפשרת לדבר, להשתעל או לנשום. תינוק מתחת לשנה דורש שיטה אחרת.','בחסימה קשה הזעיקו עזרה מיד. בהריון או כשאי אפשר להקיף את הבטן משתמשים בדחיקות חזה לפי הכשרה והמוקד.',
'אם משתעל ביעילות, עודדו שיעול והשגיחו. אין לתת אוכל או מים לדחיפת החסימה.~אם אינו יכול לדבר, להשתעל או לנשום, הזעיקו 101. הטו קדימה ותנו עד חמש טפיחות נפרדות בין השכמות בעקב כף היד; בדקו אחרי כל אחת.~אם החסימה נמשכת, תנו עד חמש דחיקות בטן פנימה ולמעלה מעל הטבור ומתחת לעצם החזה. המשיכו לסירוגין ועצרו כשהחסימה משתחררת.~באובדן הכרה הורידו למשטח קשיח והתחילו החייאה לפי ההכשרה והמוקד. מוציאים רק חפץ שרואים; אין סריקה עיוורת בפה.~לאחר דחיקות או בתסמינים מתמשכים פנו לבדיקה רפואית.',
'If coughing effectively, encourage coughing and observe. Give no food or water.~For severe obstruction call, lean forward and give up to five separate back blows, checking each time.~If unresolved, give up to five inward-and-upward abdominal thrusts above the navel and below the breastbone. Alternate and stop when relieved. Pregnancy or inability to encircle the abdomen requires chest thrusts and dispatch guidance.~If unresponsive, lower onto a firm surface and start CPR according to training and dispatch. Remove only a visible object; never sweep blindly.~Seek medical assessment after thrusts or persistent symptoms.',
'choking','לבצע דחיקות בזמן שיעול יעיל או להשתמש בשיטת מבוגר בתינוק.');
proMedical('bleeding','חתך ודימום','בדימום חזק, מהיר או שאינו נעצר, הזעקת עזרה ולחץ ישיר קודמים לניקוי הפצע.','דימום כבד, חולשה קיצונית או שינוי הכרה מחייבים הזעקת עזרה מיידית.',
'השתמשו בכפפות אם זמינות ולחצו ישירות עם תחבושת או בד נקי.~המשיכו לחץ יציב. חפץ תקוע אין להוציא או ללחוץ עליו; לחצו סביבו.~בדימום קשה פעלו לפי המוקד. חסם עורקים או חבישה המוסטטית דורשים ציוד והדרכה מתאימים; אין לעכב לחץ ישיר.~חתך קטן שדימומו נעצר אפשר לשטוף ולכסות. פצע עמוק, מלוכלך או מזוהם דורש בדיקה.',
'Use gloves if available and apply direct pressure with a clean dressing.~Maintain pressure. Do not remove or press on an embedded object; press around it.~For severe bleeding follow dispatch. Tourniquets or haemostatic dressings require suitable equipment and guidance; do not delay pressure.~Rinse and cover a minor wound after bleeding stops. Seek assessment for deep, dirty or infected wounds.','aid','להרים שוב ושוב את התחבושת או לשלוף חפץ תקוע.');
proMedical('burn','כוויה מחום','קירור מוקדם מפחית המשך פגיעה. גודל, עומק ומיקום חשובים להערכת חומרה, ולא רק הכאב.','כוויה גדולה או עמוקה, בפנים, בנתיב האוויר, מחשמל או מכימיקל דורשת עזרה דחופה.',
'התרחקו מהחום והסירו תכשיטים ובגד סמוך רק אם אינם דבוקים לעור.~קררו במים זורמים קרירים 20 דקות. אין קרח, שמן או משחות בעזרה הראשונית.~שמרו על חום שאר הגוף וכסו ברפיון בכיסוי נקי שאינו נדבק. אין לפוצץ שלפוחיות.~פנו להערכה לפי חומרה ומיקום. במיוחד בילדים הימנעו מקירור הגוף כולו.',
'Move from heat and remove jewellery or nearby clothing only if not stuck.~Cool under cool running water for 20 minutes. No ice, oils or creams during initial care.~Keep the rest of the body warm; cover loosely with a clean non-stick covering. Do not burst blisters.~Seek assessment based on severity and location. Avoid whole-body chilling, especially in children.','burn','למרוח שומן, לקרר בקרח או לתלוש בד שנדבק.');
proMedical('sprain','חשד לנקע או לפריקה','כאב ונפיחות עשויים לנבוע גם משבר. אין לאבחן לפי מראה בלבד ואין להחזיר מפרק למקום.','עיוות, חוסר תחושה, שינוי צבע או אי־יכולת להשתמש בגפה דורשים בדיקה דחופה.',
'הפסיקו פעילות והגנו מתנועה מכאיבה. אין לבדוק טווח תנועה בכוח.~אפשר לקרר דרך בד לזמן קצר תוך בדיקת העור; לא קרח ישיר.~תמכו בתנוחה שנמצאה. אל תיישרו עיוות או תנסו החזרה.~פנו לבדיקה בכאב ניכר או בספק. עקבו אחר נימול, קור ושינוי צבע.',
'Stop activity and protect from painful movement; do not force motion.~A wrapped cold pack may be used briefly while checking skin; no direct ice.~Support in the position found. Do not straighten or relocate.~Seek assessment for significant pain or uncertainty. Watch numbness, coldness or colour change.','aid','להמשיך ללכת או להחזיר מפרק מתוך הנחה שזה רק נקע.');
proMedical('heat','חשד למכת חום','בלבול, קריסה או פרכוס בחום או במאמץ יכולים להעיד על מכת חום. הזעה יכולה להימשך; היעדרה אינו תנאי.','חייגו 101 והתחילו קירור בלי להמתין למדידת חום.',
'הזעיקו עזרה, הפסיקו מאמץ ועברו למקום קריר אם בטוח.~הסירו ביגוד עודף, הרטיבו עור במים קרירים ואווררו. פעלו לפי המוקד לקירור מהיר.~בחשד למכת חום או שינוי הכרה אין לתת שתייה דרך הפה. אל תשאירו לבד.~עקבו אחר תגובה ונשימה; בהיעדר תגובה ונשימה תקינה פעלו לפי הנחיות ההחייאה.',
'Call, stop exertion and move somewhere cooler if safe.~Remove excess clothing, wet skin with cool water and fan; follow dispatch for rapid cooling.~Do not give oral fluids in suspected heatstroke or altered consciousness. Stay with the person.~Monitor response and breathing; follow CPR guidance if unresponsive and not breathing normally.','heat','לחכות להפסקת הזעה או להשקות אדם מבולבל.');

Object.assign(PRO_SOURCES,{
 tick:{name:'CDC · Tick removal',url:'https://www.cdc.gov/ticks/after-a-tick-bite/index.html'},
 asthma:{name:'St John Ambulance · Asthma',url:'https://www.sja.org.uk/first-aid-advice/asthma-attack/'},
 fracture:{name:'St John Ambulance · Fractures',url:'https://www.sja.org.uk/first-aid-advice/fractures-and-broken-bones/'},
 dehydration:{name:'St John Ambulance · Dehydration',url:'https://www.sja.org.uk/first-aid-advice/dehydration/'},
 drowning:{name:'St John Ambulance · Drowning',url:'https://www.sja.org.uk/first-aid-advice/drowning/'},
 fainting:{name:'St John Ambulance · Fainting',url:'https://www.sja.org.uk/first-aid-advice/fainting/'},
 nose:{name:'St John Ambulance · Nosebleed',url:'https://www.sja.org.uk/first-aid-advice/nosebleed/'},
 shock:{name:'St John Ambulance · Shock',url:'https://www.sja.org.uk/first-aid-advice/shock/'},
 blister:{name:'St John Ambulance · Blisters',url:'https://www.sja.org.uk/first-aid-advice/blister/'},
 sunburn:{name:'NHS · Sunburn',url:'https://www.nhs.uk/conditions/sunburn/'},
 splinter:{name:'St John Ambulance · Splinters',url:'https://www.sja.org.uk/first-aid-advice/splinters/'}
});
proMedical('sting','חשד להכשת נחש או עקיצת עקרב','התייחסו לחשד ברצינות גם כשהסימן קטן או כשהכאב מועט.','חייגו 101. אין להתקרב לבעל החיים או לנסות ללכוד אותו.',
'התרחקו מהסכנה בלי מרדף והזעיקו עזרה.~הרגיעו והמעיטו בתנועת הנפגע. הסירו תכשיטים סמוכים אם אפשר בקלות.~אין לחתוך, למצוץ, לקרר בקרח או להדק חסם עורקים.~עקבו אחר הכרה ונשימה ופעלו לפי המוקד. מסרו מיקום וזמן האירוע.',
'Move clear of danger and call for help; do not pursue the animal.~Reassure and minimize movement; remove nearby jewellery if easily done.~Do not cut, suck, apply ice or use a tourniquet.~Monitor response and breathing. Tell dispatch the location and time.','snake','לעכב פינוי כדי לזהות או ללכוד את בעל החיים.');
proMedical('fracture','חשד לשבר — תמיכה והזעקת עזרה','גם ללא עיוות נראה לעין ייתכן שבר.','פציעה קשה, דימום, עצם חשופה או שינוי בתחושה מחייבים עזרה דחופה.',
'הפסיקו פעילות. אין להזיז או ליישר בכוח.~תמכו בגפה בתנוחה שנמצאה עם ריפוד; קיבוע דורש הכשרה.~כסו פצע פתוח בעדינות; אל תדחפו עצם פנימה.~הזעיקו עזרה בהתאם לחומרה. עקבו אחר צבע, חום ותחושה מעבר לפציעה.',
'Stop activity; do not force movement or straighten.~Support in the position found with padding; splinting requires training.~Cover an open wound; do not push bone back in.~Obtain help appropriate to severity. Monitor colour, warmth and sensation beyond the injury.','fracture','בדיקת השבר על ידי כיפוף הגפה.');
proMedical('hypothermia','חשד להיפותרמיה','קור מסוכן עלול להתפתח גם במזג אוויר שאינו קפוא, במיוחד ברטיבות וברוח.','בלבול, ישנוניות או נשימה איטית בקור הם סימני חירום.',
'העבירו למחסה בטוח, הזעיקו עזרה וטפלו בעדינות.~החליפו בגדים רטובים אם אפשר והוסיפו בידוד מתחת לגוף ומסביבו.~אין אמבט חם, שפשוף גפיים או אלכוהול. משקה חמים רק לערני הבולע בבטחה.~אל תשאירו לבד. עקבו אחר הנשימה ופעלו לפי המוקד.',
'Move to safe shelter, call for help and handle gently.~Replace wet clothes where possible and insulate beneath and around the body.~No hot bath, limb rubbing or alcohol. Warm drinks only if fully alert and swallowing safely.~Stay with the person, monitor breathing and follow dispatch.','cold','חימום אגרסיבי או התעלמות מירידה בערנות.');
proMedical('nosebleed','דימום מהאף','לרוב ניתן להאט את הדימום בלחץ נכון ומתמשך.','דימום כבד, קושי בנשימה, פגיעת ראש או דימום ממושך דורשים עזרה רפואית.',
'הושיבו עם הראש מוטה מעט קדימה.~צבטו את החלק הרך של האף ברציפות 10–15 דקות, ונשמו דרך הפה.~אין להטות ראש לאחור או לבדוק כל דקה.~אם הדימום אינו נפסק, או יש חולשה או דימום רב, פנו לעזרה.',
'Sit leaning slightly forward.~Pinch the soft part of the nose continuously for 10–15 minutes and breathe through the mouth.~Do not tilt the head back or release repeatedly to check.~Get medical help if bleeding persists, is heavy or causes weakness.','nose','להטות את הראש לאחור ולבלוע דם.');
proMedical('dehydration','התייבשות','צמא, יובש ומיעוט שתן עשויים להצביע על חוסר נוזלים. בלבול אינו סימן קל.','שינוי הכרה, קריסה או חוסר יכולת לשתות מחייבים עזרה דחופה.',
'הפסיקו מאמץ ועברו לצל או למקום קריר.~לערני הבולע בבטחה הציעו לגימות קטנות ותכופות. אפשר תמיסת מלחים מוכנה לפי הוראותיה.~אל תכריחו שתייה ואל תתנו מלח יבש או טבליות מלח כטיפול מאולתר.~אם אין שיפור או יש הקאות חוזרות, פנו לעזרה. בחשד למכת חום חייגו 101.',
'Stop exertion and move somewhere cooler.~Offer small frequent sips only if alert and swallowing safely; use prepared oral rehydration as directed.~Do not force fluids or improvise with dry salt or salt tablets.~Seek help if not improving or repeatedly vomiting. Suspected heatstroke needs emergency care.','dehydration','להמשיך במסלול למרות החמרה או להשקות אדם מבולבל.');
proMedical('tick','הסרת קרצייה','הסרה מוקדמת ועדינה מפחיתה את משך החשיפה.','פריחה או חום בימים או בשבועות שלאחר העקיצה מצריכים פנייה לרופא.',
'אחזו בפינצטה נקייה קרוב ככל האפשר לעור, בלי למעוך את גוף הקרצייה.~משכו לאט בלחץ יציב, ללא סיבוב או טלטול.~נקו ידיים ואת האזור. אין לחפור בעור אם חלק אינו יוצא בקלות.~רשמו תאריך ומקום ובדקו את שאר הגוף. אין שמן, חום או שרפה.',
'Use clean fine-tipped tweezers close to the skin without squeezing the body.~Pull steadily without twisting or jerking.~Clean the area and hands. Do not dig for parts that will not come out easily.~Record date and location and check the rest of the body. No oil, heat or burning.','tick','מריחת חומר או שרפה כדי לגרום לקרצייה להשתחרר.');
proMedical('beesting','עקיצת דבורה או צרעה','יש להבחין בין תגובה מקומית לבין תגובה אלרגית מסוכנת.','קושי בנשימה, נפיחות בלשון או בגרון, או התמוטטות: חייגו 101 מיד.',
'התרחקו מהחרקים. הסירו עוקץ נראה בהקדם, למשל בגירוד עדין הצדה.~שטפו ונקו; אפשר קומפרס קר עטוף בבד.~בתגובה קשה סייעו בשימוש במזרק אדרנלין שנרשם לנפגע לפי הוראות המכשיר והמוקד.~עקבו אחר נשימה וערנות. עקיצות בפה או בגרון דורשות עזרה דחופה.',
'Move away from insects and promptly remove a visible stinger, for example by scraping sideways.~Clean the site; a cloth-wrapped cold compress may help.~For a severe reaction help use the person’s prescribed adrenaline auto-injector following its instructions and dispatch.~Monitor breathing and alertness. Mouth or throat stings need urgent help.','bites','להמתין לפריחה לפני הזעקת עזרה בקשיי נשימה.');
proMedical('blisters','שלפוחית מחיכוך','טיפול מוקדם בחיכוך יכול למנוע פצע שמקשה על ההליכה.','סימני זיהום, סוכרת או בעיית זרימת דם מצריכים ייעוץ רפואי.',
'הפסיקו את החיכוך והחליפו גרב רטובה.~נקו בעדינות ויבשו. אל תפוצצו שלפוחית.~כסו בחבישה מתאימה ורפדו מסביבה בלי לחץ עליה.~אם נפתחה, אל תתלשו את העור. בדקו אודם מתפשט, מוגלה או החמרה.',
'Stop the rubbing and change wet socks.~Clean gently and dry; do not burst the blister.~Cover with a suitable dressing and pad around it without pressure.~If it opens, do not peel the skin. Watch spreading redness, pus or worsening pain.','blister','ניקוב יזום בשטח או המשך הליכה באותו חיכוך.');
proMedical('splinter','קוץ או שבב שטחי','הוצאה עצמית מתאימה רק לשבב קטן, שטחי ונגיש.','קוץ עמוק, ליד העין, דימום משמעותי או ספק מצריכים טיפול מקצועי.',
'שטפו ידיים ואת האזור. אל תחפרו בעור.~אם הקצה גלוי ונגיש, משכו בעדינות בפינצטה נקייה בכיוון כניסתו.~נקו וכסו. הפסיקו אם אינו יוצא בקלות.~פנו לייעוץ לגבי פצע מזוהם, החמרה או צורך בעדכון טטנוס.',
'Wash hands and the area; do not dig into skin.~If superficial with an accessible end, pull gently with clean tweezers along its entry direction.~Clean and cover. Stop if it does not come out easily.~Seek advice for contamination, worsening symptoms or tetanus protection.','splinter','חפירה עמוקה או ניסיון להוציא גוף זר מהעין.');
proMedical('eye','גוף זר או פגיעה בעין','אבק חופשי שונה מגוף נעוץ או מפגיעה במהירות גבוהה.','שינוי בראייה, כאב חזק, חומר כימי או גוף נעוץ: עזרה רפואית דחופה.',
'אל תשפשפו ואל תלחצו על העין.~אבק חופשי אפשר לשטוף במים נקיים בזרימה עדינה.~אין להוציא גוף נעוץ או להשתמש בפינצטה בעין.~בחשיפה כימית התחילו שטיפה ממושכת והזעיקו עזרה. אל תעכבו כדי למצוא חומר מיוחד.',
'Do not rub or press the eye.~Loose dust may be rinsed with a gentle flow of clean water.~Do not remove embedded objects or use tweezers in the eye.~For chemicals start prolonged rinsing and get urgent help; do not delay seeking a special solution.','eye,chemical','שפשוף, לחץ או ניסיון לשלוף גוף נעוץ.');
proMedical('carrying','פינוי פצוע — מתי לא להזיז','נשיאה מאולתרת עלולה להחמיר פציעה. ברירת המחדל היא טיפול במקום בטוח והזעקת חילוץ.','אם קיימת סכנה מיידית, פעלו לפי המוקד להתרחקות המינימלית האפשרית.',
'בדקו סכנות לכם ולנפגע וחייגו 101 לפי הצורך.~אל תושיבו או תעמידו נפגע לאחר חבלה משמעותית כדי לבדוק אם הוא יכול.~שמרו על נשימה, חום גוף והשגחה. מסרו מיקום מדויק ודרך גישה.~תכננו פינוי עם צוות מוסמך. נשיאה וקיבוע נלמדים בתרגול מעשי מודרך.',
'Assess hazards and call for help as needed.~Do not sit or stand someone after major trauma just to test mobility.~Monitor breathing, keep warm and provide accurate location and access details.~Arrange evacuation with trained rescuers. Carrying and immobilization require practical training.','fracture','נשיאה מאולתרת ללא צורך או הכשרה.');
proMedical('shock','חשד להלם רפואי','חיוורון, עור קר ולח, חולשה וירידה בערנות עלולים להעיד על הפרעה מסוכנת באספקת הדם.','זהו מצב חירום רפואי. חייגו 101.',
'הזעיקו עזרה וטפלו בגורם נראה, כגון דימום חיצוני, לפי הכשרה.~השכיבו אם ניתן ונוח לנשימה; אל תכפו תנוחה שמקשה לנשום או גורמת כאב.~שמרו חום גוף והשגיחו. אין אוכל או שתייה.~עקבו אחר נשימה והכרה והיערכו להחייאה לפי המוקד.',
'Call for help and address visible causes such as external bleeding within your training.~Lie the person down if tolerated; never force a position that worsens breathing or pain.~Keep warm and stay with them. No food or drink.~Monitor response and breathing and follow dispatch if CPR is needed.','shock','בלבול בין הלם רפואי לבין בהלה בלבד.');
proMedical('fainting','עילפון','אובדן הכרה קצר מחייב בדיקת נשימה ומעקב, גם אם נראה שהאדם התאושש.','ללא התאוששות מהירה, בפציעה או בכאב חזה או קוצר נשימה חייגו 101.',
'מנעו נפילה נוספת והשכיבו במקום בטוח.~בדקו תגובה ונשימה. בהיעדר נשימה תקינה חייגו והתחילו החייאה.~אם נושם אך אינו מגיב, פעלו לפי המוקד לשמירת נתיב האוויר.~לאחר התאוששות השאירו במנוחה וקומו בהדרגה. אין להשקות מי שאינו ערני לחלוטין.',
'Prevent another fall and lie the person somewhere safe.~Check response and breathing. If not breathing normally, call and begin CPR.~If breathing but unresponsive, follow dispatch to maintain the airway.~After recovery rest and rise slowly. Do not give fluids unless fully alert.','fainting','להעמיד מיד, לסטור או לשפוך מים על הפנים.');
proMedical('seizure','פרכוס','המטרה היא למנוע חבלה, למדוד זמן ולשמור על הנשימה לאחר הפרכוס.','חייגו 101 בפרכוס ראשון, מעל 5 דקות, ברצף ללא התאוששות, בפציעה או בקושי נשימתי.',
'הרחיקו חפצים ורפדו מתחת לראש. מדדו את זמן תחילת הפרכוס.~אין לרסן ואין להכניס דבר לפה.~לאחר סיום התנועות בדקו נשימה; אם נושם, השכיבו על הצד כשאפשר בבטחה.~הישארו עד התאוששות ועזרה. אין שתייה או אוכל לפני ערנות מלאה.',
'Clear nearby hazards, cushion the head and time the seizure.~Do not restrain or put anything in the mouth.~After movements stop, check breathing; if breathing, turn onto the side when safe.~Stay through recovery and help arriving. No food or drink until fully alert.','seizure','להחזיק בכוח או לנסות לפתוח את הפה.');
proMedical('chemicalburn','חשיפה לחומר כימי בעור','יש להגן גם על המסייע ולמנוע המשך חשיפה.','הזעיקו עזרה רפואית מיד ופעלו לפי הוראות המוקד והחומר.',
'התרחקו מהמקור בלי להיחשף והסירו בזהירות בגד מזוהם.~הברישו אבקה יבשה בעדינות לפני שטיפה, בלי מגע ביד חשופה.~שטפו בהרבה מים קרירים או פושרים. השטיפה עשויה להידרש כשעה; המשיכו לפי המוקד.~אין לנטרל בחומר כימי אחר או למרוח משחה. מסרו לצוות את שם החומר אם ידוע.',
'Leave the source without exposing yourself and carefully remove contaminated clothing.~Gently brush dry powder away before rinsing, without bare-hand contact.~Rinse with plenty of cool or lukewarm water; about an hour may be needed. Follow dispatch.~Do not neutralize with another chemical or apply cream. Tell responders the substance if known.','chemical','ניסיון לנטרל חומצה בבסיס או להפך.');
proMedical('animalbite','נשיכת בעל חיים','גם פצע קטן עשוי להצריך הערכה לזיהום, טטנוס וכלבת.','דימום קשה או פציעה משמעותית: חייגו 101. פנו בהקדם לייעוץ רפואי אחרי נשיכה.',
'התרחקו מהחיה בלי לנסות ללכוד אותה.~אם אין דימום קשה, שטפו היטב במים זורמים וסבון.~כסו בחבישה נקייה; דימום משמעותי דורש לחץ ישיר ועזרה.~מסרו לצוות זמן, מקום וסוג חיה אם ידוע. אל תחכו לתסמינים כדי לברר צורך בטיפול.',
'Move away without trying to capture the animal.~If not bleeding severely, wash thoroughly with running water and soap.~Cover with a clean dressing; significant bleeding needs direct pressure and help.~Report time, place and species if known. Do not wait for symptoms before seeking advice.','animal','להניח שנשיכה קטנה אינה דורשת בירור.');
proMedical('headinjury','פגיעת ראש','לא כל סיבוך נראה מיד. יש לעקוב אחר שינוי בהתנהגות ובתפקוד.','ירידה בהכרה, פרכוס, חולשה, הקאות חוזרות או החמרה: חייגו 101.',
'הפסיקו פעילות ומנעו חבלה נוספת.~צמצמו תנועה בחשד לפגיעת צוואר; שמירת הנשימה קודמת לפי המוקד.~פנו להערכה רפואית לפי חומרת הפגיעה, במיוחד בנטילת מדללי דם.~אין חזרה לספורט באותו יום בחשד לזעזוע מוח. דאגו להשגחה והנחיות רפואיות.',
'Stop activity and prevent another impact.~Minimize movement if neck injury is suspected; airway care follows dispatch priorities.~Seek assessment according to severity, especially with blood-thinning medication.~No same-day return to sport with suspected concussion. Arrange supervision and medical instructions.','head','להמשיך פעילות כי הנפגע עדיין מדבר.');
proMedical('drowning','אירוע טביעה — עזרה בטוחה','המסייע חייב להישאר בטוח. חילוץ במים דורש הכשרה.','הזעיקו מציל ו־101. אין להיכנס למים מסוכנים.',
'הושיטו אמצעי ציפה או עזרה ממקום יציב בלי לסכן את עצמכם.~לאחר חילוץ בטוח בדקו תגובה ונשימה.~אם אינו נושם כרגיל, פעלו מיד לפי המוקד. בטביעה הנשמות חשובות; מי שהוכשר מבצע החייאת טביעה לפי הכשרתו.~הביאו AED, עקבו אחר הוראותיו ודאגו להערכה רפואית גם לאחר שיפור.',
'Call lifeguards and emergency services; offer flotation from a stable safe position.~After safe rescue check response and breathing.~If not breathing normally follow dispatch immediately. Rescue breaths matter in drowning; trained rescuers follow drowning CPR training.~Bring an AED and follow its prompts. Arrange medical assessment even after improvement.','drowning','כניסה מסוכנת למים או ניסיון להוציא מים מהגוף במקום החייאה.');
proMedical('asthma','התקף אסתמה','הכירו מראש את תוכנית הטיפול האישית של המשתתף ואת מקום המשאף.','מצוקה קשה, החמרה, תשישות, התקף ראשון או היעדר משאף: חייגו 101.',
'הפסיקו מאמץ והושיבו בתנוחה נוחה לנשימה.~סייעו במשאף ההקלה שנרשם לנפגע לפי התוכנית האישית וההנחיות; השתמשו בספייסר אם מתאים וזמין.~אל תשאירו לבד. אם אין שיפור מהיר, הזעיקו עזרה.~עקבו אחר נשימה ותגובה. לאחר שיפור יש לקבל ייעוץ רפואי בהקדם.',
'Stop exertion and sit in a comfortable breathing position.~Help use the person’s prescribed reliever according to their individual plan; use a suitable spacer if available.~Stay with them and call if not improving promptly.~Monitor breathing and response. Arrange prompt medical review after improvement.','asthma','לתת מינון אחיד לכל סוגי המשאפים או לעכב הזעקת עזרה.');
proMedical('sunburn','כוויית שמש','מניעת חשיפה נוספת חשובה גם כשכבר הופיע כאב.','שלפוחיות, מחלה כללית או כווייה בתינוק או בילד קטן מחייבות ייעוץ רפואי.',
'עברו לצל וכסו את העור מבגד רפוי.~קררו בעדינות במים קרירים או מגבת לחה; אין קרח ישיר.~שתו אם ערניים, והימנעו מקילוף עור או פיצוץ שלפוחיות.~בחרו תכשיר לחות מתאים בעזרת רוקח. בהחמרה או סימני מחלת חום פנו לעזרה.',
'Move to shade and cover with loose clothing.~Cool gently with cool water or a damp towel; no direct ice.~Drink if alert; do not peel skin or burst blisters.~Ask a pharmacist about a suitable moisturizer. Seek help for worsening symptoms or heat illness.','sunburn','להמשיך להיחשף לשמש או לקרר בקרח ישירות.');
