/* Scout's Guide visual integration. Original third-party images retain their licences. */
const vText=(he,en)=>L({he,en});
const vEscape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const vTopic=id=>Object.entries(CONTENT).flatMap(([key,c])=>c.items.map(it=>({key,it}))).find(x=>x.it.id===id);
const vCropBounds={reef:[[0,510],[515,1030],[1030,1591]],bowline:[[0,472],[480,817],[825,1181]],clove:[[0,445],[451,843],[850,1318]]};
const vSequences={
 reef:[['ההצלבה הראשונה','יוצרים את החצי הראשון של הקשר. עקבו אחר שני החבלים בציור; הצבעים עוזרים לשמור על זהות כל חבל.','First crossing','Form the first half knot. Follow each coloured rope in the drawing.'],['ההצלבה ההפוכה','מבצעים את החצי השני בכיוון ההפוך, לפי החץ. שומרים על שני החבלים מובחנים כדי לא לחזור בטעות על אותו כיוון.','Reverse the crossing','Make the second half knot in the opposite direction, following the arrow.'],['מסדרים ומהדקים','מהדקים בעדינות ומסדרים את הקשר שטוח, כמו בתוצאה. שני הקצוות של כל חבל יוצאים יחד מאותו צד.','Dress the knot','Tighten gently and dress the knot flat. The two ends of each rope emerge together on the same side.']],
 bowline:[['יוצרים לולאה קטנה','יוצרים לולאה קטנה בחלק הארוך. מעלים את הקצה העובד דרכה, בכיוון החץ. הלולאה הגדולה שמתחת תישאר הלולאה הקבועה.','Form the small loop','Make a small loop in the standing rope. Bring the working end through it as shown by the arrow.'],['מקיפים וחוזרים','מעבירים את הקצה מאחורי החלק הארוך ומחזירים אותו דרך הלולאה הקטנה. עקבו אחר החץ הכחול בלי לשנות את כיוון הלולאה.','Around and back through','Pass the working end around the standing rope and back through the small loop, following the blue arrow.'],['מסדרים את הקשר','מחזיקים את הלולאה הגדולה ומושכים בהדרגה את החלק הארוך. משווים את מסלול החבל לתוצאה ומשאירים קצה חופשי מספיק.','Dress the bowline','Hold the large loop and gradually pull the standing rope. Compare the rope path with the final drawing and leave an adequate tail.']],
 clove:[['כריכה ראשונה','מקיפים את המוט פעם אחת. משאירים קצה עובד שאפשר להמשיך איתו לכריכה השנייה.','First turn','Wrap the rope once around the pole, leaving enough working end for another turn.'],['כריכה שנייה והעברה מתחת','מקיפים שוב, מצטלבים מעל הכריכה הראשונה ומשחילים את הקצה מתחת לכריכה האחרונה, לפי החץ.','Second turn and tuck','Wrap again, cross over the first turn and tuck the end under the final turn as shown.'],['מהדקים סביב המוט','מושכים בשני החלקים ומסדרים את הכריכות צמודות למוט. משווים לציור הסופי; הקשר עלול להחליק תחת עומס משתנה.','Tighten around the pole','Pull both ends and dress the turns against the pole. Compare with the final drawing; the hitch can slip under changing loads.']]
};
// Standard names improve findability while retaining original English identifiers and content.
CONTENT.knots.items.find(x=>x.id==='reef').title.he='קשר שטוח (ריף)';
CONTENT.knots.items.find(x=>x.id==='bowline').title.he='קשר הצלה';
CONTENT.knots.items.find(x=>x.id==='clove').title.he='קשר מוט';
function searchableTopic(it){return [L(it.title),L(it.lead),...it.steps.map(st=>L(st.text)),...(it.tips||[]).map(L),...(it.safety||[]).map(L),...(SCOUT_VISUALS[it.id]||[]).map(a=>L(a.title))].join(' ').toLowerCase();}
function visualThumb(it){const a=SCOUT_VISUALS[it.id]?.[0];return a?`<img class="visual-thumb" src="${a.src}" alt="${vEscape(L(a.title))}" loading="lazy">`:`<div class="ic">${it.icon}</div>`;}
function visualCredit(a){return `<small class="visual-credit"><a href="${a.source}" target="_blank" rel="noopener">${a.credit.split(' · ').slice(0,-1).join(' · ')}</a> · <a href="${a.license}" target="_blank" rel="noopener">${a.credit.split(' · ').at(-1)}</a></small>`;}
function visualGuide(it){
 const aa=SCOUT_VISUALS[it.id];if(!aa)return it.id==='morse'?`<div class="visual-actions"><button class="btn" onclick="openMorseTool()">${vText('פתיחת מתרגם מורס','Open Morse translator')}</button></div>`:'';
 if(vSequences[it.id])return `<section class="visual-guide"><header><h2>${vText('כך קושרים — שלב אחר שלב','How to tie — step by step')}</h2><small>${vText('3 שלבים','3 steps')}</small></header><div id="sequence-${it.id}" class="sequence-shell"></div><details class="visual-full"><summary>${vText('הצגת הרצף המלא · משמאל לימין','Show the full sequence · left to right')}</summary>${visualPlate(it.id,0)}</details>${visualCredit(aa[0])}</section>`;
 return `${it.id==='leanto'?'<p class="hint">'+vText('להשוואה: האיור החדש מציג מחסה סגור משני צדדים; ההוראות בהמשך מתארות מחסה חד־צדדי (לין־טו).','For comparison: this illustration shows a two-sided debris hut; the instructions below describe a one-sided lean-to.')+'</p>':''}<section class="visual-guide"><header><h2>${vText('רואים איך זה עובד','See how it works')}</h2><small>${aa.length>1?aa.length+' '+vText('איורים','illustrations'):''}</small></header>${aa.length>1?`<div class="visual-pills">${aa.map((a,i)=>`<button aria-pressed="${i===0}" onclick="selectVisual('${it.id}',${i})" data-visual-index="${i}">${vEscape(L(a.title))}</button>`).join('')}</div>`:''}<div id="visual-stage-${it.id}">${visualPlate(it.id,0)}<p class="visual-caption">${vEscape(L(aa[0].title))} · ${vText('לחצו על האיור להגדלה','Select the illustration to enlarge')}</p>${visualCredit(aa[0])}</div></section>`;
}
function visualPlate(id,i){const a=SCOUT_VISUALS[id][i];return `<button class="visual-plate" onclick="zoomVisual('${id}',${i})" aria-label="${vEscape(vText('הגדלת איור: ','Enlarge illustration: ')+L(a.title))}"><img src="${a.src}" alt="${vEscape(L(a.title))}" width="${a.width}" height="${a.height}" style="height:auto"></button>`;}
function selectVisual(id,i){const a=SCOUT_VISUALS[id][i],node=$('visual-stage-'+id);node.innerHTML=visualPlate(id,i)+`<p class="visual-caption">${vEscape(L(a.title))} · ${vText('לחצו על האיור להגדלה','Select to enlarge')}</p>`+visualCredit(a);node.closest('section').querySelectorAll('[data-visual-index]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.visualIndex)===i));}
function renderSequence(id,i=0){
 const a=SCOUT_VISUALS[id][0],st=vSequences[id][i],isHe=S.lang==='he',node=$('sequence-'+id);if(!node)return;const [x,right]=vCropBounds[id][i],cw=right-x;
 node.innerHTML=`<div class="sequence-focus"><div class="sequence-crop" style="aspect-ratio:${cw}/${a.height};max-width:${Math.min(360,cw/a.height*340)}px"><img src="${a.src}" alt="${vEscape(st[isHe?0:2])}" style="width:${a.width/cw*100}%;transform:translateX(-${x/a.width*100}%)"></div></div><div class="sequence-copy" aria-live="polite"><h3>${i+1}. ${vEscape(st[isHe?0:2])}</h3><p>${vEscape(st[isHe?1:3])}</p></div><div class="sequence-controls"><button class="btn ghost" ${i===0?'disabled':''} onclick="renderSequence('${id}',${i-1})">${vText('הקודם','Previous')}</button><div class="sequence-dots">${[0,1,2].map(j=>`<button aria-label="${vText('שלב','Step')} ${j+1}" aria-pressed="${j===i}" onclick="renderSequence('${id}',${j})">${j+1}</button>`).join('')}</div><button class="btn" ${i===2?'disabled':''} onclick="renderSequence('${id}',${i+1})">${vText('הבא','Next')}</button></div>`;
}
function zoomVisual(id,i){const a=SCOUT_VISUALS[id][i];$('visualZoomTitle').textContent=L(a.title);$('visualZoomImage').src=a.src;$('visualZoomImage').alt=L(a.title);$('visualZoomCredit').innerHTML=visualCredit(a);$('visualZoom').showModal();}
let detailOrigin='home';
const originalOpenItem=openItem;openItem=function(key,id){const active=document.querySelector('.screen.active')?.id;if(active&&active!=='detail')detailOrigin=active;originalOpenItem(key,id);if(currentItem===id&&$('detail').classList.contains('active')&&vSequences[id])renderSequence(id);};
const originalRenderHome=renderHome;renderHome=function(){
 originalRenderHome();const f=$('visualFeatured');if(!f)return;
 f.innerHTML=`<section class="visual-intro"><div class="visual-eyebrow">${vText('המדריך המאויר שלך','YOUR ILLUSTRATED FIELD GUIDE')}</div><h2>${vText('ללמוד קשרים, צעד אחר צעד','Learn knots, one step at a time')}</h2><p>${vText('בחרו קשר, עקבו אחר החבל ותרגלו בקצב שלכם.','Choose a knot, follow the rope and practise at your own pace.')}</p><div class="visual-featured-grid">${['reef','bowline','clove'].map(id=>{const t=vTopic(id);return `<button class="visual-feature" onclick="openItem('knots','${id}')"><img src="${SCOUT_VISUALS[id][0].src}" alt="${vEscape(L(t.it.title))}"><span>${vEscape(L(t.it.title))}<small>${vText('לפתיחת ההדרכה ←','Open the guide →')}</small></span></button>`;}).join('')}</div><div class="visual-actions"><button class="btn" onclick="openVisualLibrary()">${vText('לכל ההדרכות המאוירות','All illustrated guides')}</button><button class="btn ghost" onclick="openMorseTool()">${vText('כלי מורס · כתיבה והשמעה','Morse · translate and play')}</button></div></section>`;
 const covers={knots:'reef',fire:'build',shelter:'tarp',navigation:'terrain',signals:'mirror',gear:'repairkit',nature:'weather'};
 for(const [key,id] of Object.entries(covers)){const card=$('catGrid').querySelector(`[onclick="openCat('${key}')"]`);if(card){const img=document.createElement('img');img.src=SCOUT_VISUALS[id][0].src;img.alt='';img.className='category-art';img.loading='lazy';card.insertBefore(img,card.querySelector('h3'));}}
};
function openVisualLibrary(cat='all'){
 const ids=Object.keys(SCOUT_VISUALS).filter(id=>cat==='all'||vTopic(id).key===cat);
 $('visualLibraryBody').innerHTML=`<h1>${vText('ההדרכות המאוירות','Illustrated guides')}</h1><p class="hint">${vText('קשרים, אש, מחסה וכלים להבנת השטח. בחרו נושא כדי לפתוח את ההדרכה.','Knots, fire, shelter and field skills. Choose a topic to open its guide.')}</p><div class="visual-toolbar">${['all',...new Set(Object.keys(SCOUT_VISUALS).map(id=>vTopic(id).key))].map(k=>`<button aria-pressed="${k===cat}" onclick="openVisualLibrary('${k}')">${k==='all'?vText('הכול','All'):L(CONTENT[k].title)}</button>`).join('')}</div><div class="visual-library-grid">${ids.map(id=>{const {it,key}=vTopic(id),a=SCOUT_VISUALS[id][0];return `<button class="visual-feature" onclick="openItem('${key}','${id}')"><img src="${a.src}" alt="${vEscape(L(a.title))}" loading="lazy"><span>${vEscape(L(it.title))}<small>${L(CONTENT[key].title)} · ${SCOUT_VISUALS[id].length} ${vText('איורים','illustrations')}</small></span></button>`;}).join('')}</div>`;lastList=null;go('visualLibrary');
}
let morsePlayer=null,morseResult='',morseValid=false;
function normalizeHebrew(s){const finals={'ך':'כ','ם':'מ','ן':'נ','ף':'פ','ץ':'צ'};return s.replace(/[\u0591-\u05bd\u05bf-\u05c7]/g,'').replace(/[ךםןףץ]/g,c=>finals[c]);}
function openMorseTool(){
 $('morseToolBody').innerHTML=`<h1>${vText('מורס — כותבים ושומעים','Morse — translate and listen')}</h1><p class="hint">${vText('כלי מקומי לתרגול. ההשמעה אינה שולחת הודעה או מזעיקה עזרה.','An offline practice tool. Playback does not send a message or call for help.')}</p><div class="field-tool"><label for="morseMode">${vText('כיוון התרגום','Translation direction')}</label><select id="morseMode" onchange="updateMorse()"><option value="encode">${vText('טקסט למורס','Text to Morse')}</option><option value="decode">${vText('מורס לטקסט','Morse to text')}</option></select><label for="morseCharset">${vText('שפת האותיות','Alphabet')}</label><select id="morseCharset" onchange="updateMorse()"><option value="itu">English / International</option><option value="hebrew">עברית</option><option value="arabic">العربية</option><option value="cyrillic">Русский</option><option value="latin-ext">Español / Latin</option></select><label for="morseInput">${vText('הודעה (עד 300 תווים)','Message (up to 300 characters)')}</label><textarea id="morseInput" maxlength="300" dir="auto" oninput="updateMorse()">SOS</textarea><p class="hint">${vText('בפענוח: רווח בין אותיות, / בין מילים. אותיות סופיות בעברית מומרות לצורת הבסיס.','Decoding: space between letters, / between words. Hebrew final letters are normalized.')}</p><div id="morseOutput" class="morse-output" aria-live="polite"></div><p id="morseError" class="morse-error" role="status"></p><label for="morseSpeed">${vText('מהירות','Speed')}: <span id="morseSpeedValue">12</span> WPM</label><input id="morseSpeed" type="range" min="5" max="30" value="12" oninput="stopMorse();$('morseSpeedValue').textContent=this.value"><div class="morse-indicator"><progress id="morseProgress" max="1" value="0" aria-label="${vText('התקדמות השמעה','Playback progress')}"></progress></div><div class="visual-actions"><button id="morsePlay" class="btn" onclick="playMorse()">▶ ${vText('השמעה','Play')}</button><button class="btn ghost" onclick="stopMorse()">■ ${vText('עצירה','Stop')}</button><button id="morseSave" class="btn ghost" onclick="saveMorseWav()">${vText('שמירת שמע','Save audio')}</button></div></div><details class="tips" open><summary>${vText('טבלת האותיות','Alphabet chart')}</summary><div id="morseTable" class="morse-table"></div></details><p class="hint">MorseCodeApp · MIT · <a href="credits.html">${vText('מקורות ורישיונות','Sources and licences')}</a></p>`;go('morseTool');updateMorse();
}
function updateMorse(){stopMorse();const mode=$('morseMode').value,charset=$('morseCharset').value,input=normalizeHebrew($('morseInput').value),r=mode==='encode'?ScoutMorse.encodeDetailed(input,{charset,fallbackCharsets:charset==='itu'?[]:['itu']}):ScoutMorse.decodeDetailed(input,{charset});morseValid=r.valid&&input.trim().length>0;morseResult=mode==='encode'?r.morse:input.trim();$('morseOutput').textContent=mode==='encode'?r.morse:r.text;$('morseOutput').dir=mode==='decode'&&['hebrew','arabic'].includes(charset)?'rtl':'ltr';$('morseOutput').style.textAlign=mode==='decode'&&['hebrew','arabic'].includes(charset)?'right':'left';$('morseError').textContent=r.valid?'':vText('תווים או סימנים שלא זוהו: ','Unrecognized characters or patterns: ')+r.errors.join(' ');$('morsePlay').disabled=!morseValid;$('morseSave').disabled=!morseValid;const map=ScoutMorse.getCharset(charset).charToMorse;$('morseTable').innerHTML=Object.entries(map).map(([c,m])=>`<div><b>${vEscape(c)}</b><code>${vEscape(m)}</code></div>`).join('');}
async function playMorse(){if(!morseValid)return;stopMorse();const player=new ScoutMorse.MorsePlayer({wpm:Number($('morseSpeed').value),volume:30,onProgress:(n,total)=>{if($('morseProgress'))$('morseProgress').value=total?n/total:0;},onEnd:()=>{if($('morseProgress'))$('morseProgress').value=1;}});morsePlayer=player;try{await player.play(morseResult,{morse:true});}catch(e){$('morseError').textContent=vText('לא ניתן להפעיל שמע בדפדפן הזה.','Audio playback is unavailable in this browser.');}}
function stopMorse(){if(morsePlayer){morsePlayer.dispose();morsePlayer=null;}if($('morseProgress'))$('morseProgress').value=0;}
function saveMorseWav(){if(morseValid)ScoutMorse.downloadWav(morseResult,{morse:true,wpm:Number($('morseSpeed').value),volume:30,filename:'scout-morse.wav'});}
const originalGo=go;go=function(screen){if(screen!=='morseTool')stopMorse();return originalGo(screen);};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopMorse();});
let personalGear;try{personalGear=JSON.parse(store.get('sg_personal_gear')||'[]');if(!Array.isArray(personalGear))personalGear=[];}catch{personalGear=[];}
const originalChecklist=renderChecklist;renderChecklist=function(){originalChecklist();const section=document.createElement('section');section.className='field-tool';section.innerHTML=`<h2>${vText('הציוד האישי שלי','My extra gear')}</h2><form class="personal-gear-form" onsubmit="event.preventDefault();addPersonalGear()"><input id="personalGearInput" maxlength="100" aria-label="${vText('פריט נוסף','Extra item')}" placeholder="${vText('למשל: מטען נייד','For example: power bank')}"><button class="btn" type="submit">${vText('הוספה','Add')}</button></form><div>${personalGear.map((g,i)=>`<div class="personal-gear-row"><button class="item" aria-pressed="${!!g.checked}" onclick="togglePersonalGear(${i})"><span>${g.checked?'☑':'☐'}</span><span style="${g.checked?'text-decoration:line-through;opacity:.6':''}">${vEscape(g.name)}</span></button><button class="remove-gear" aria-label="${vEscape(vText('מחיקת ','Remove ')+g.name)}" onclick="removePersonalGear(${i})">✕</button></div>`).join('')}</div><small class="hint">${vText('נשמר במכשיר ובדפדפן הזה.','Saved in this browser on this device.')}</small>`;$('checkItems').appendChild(section);};
function savePersonalGear(){store.set('sg_personal_gear',JSON.stringify(personalGear));renderChecklist();}
function addPersonalGear(){const name=$('personalGearInput').value.trim();if(name&&personalGear.length<100){personalGear.push({name,checked:false});savePersonalGear();$('personalGearInput').focus();}}
function togglePersonalGear(i){personalGear[i].checked=!personalGear[i].checked;savePersonalGear();}
function removePersonalGear(i){personalGear.splice(i,1);savePersonalGear();}
document.addEventListener('DOMContentLoaded',()=>{
 const host=$('home').parentElement;
 for(const [id,body] of [['visualLibrary','visualLibraryBody'],['morseTool','morseToolBody']]){const s=document.createElement('section');s.className='screen';s.id=id;s.innerHTML=`<button class="backbtn" onclick="go('home')">${vText('→ חזרה לבית','← Back home')}</button><div id="${body}"></div>`;host.appendChild(s);}
 const d=document.createElement('dialog');d.id='visualZoom';d.innerHTML=`<header><strong id="visualZoomTitle"></strong><button onclick="$('visualZoom').close()" autofocus>${vText('סגירה ✕','Close ✕')}</button></header><img id="visualZoomImage" alt=""><div id="visualZoomCredit"></div>`;document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d)d.close();});
 const footer=document.createElement('div');footer.className='visual-footer';footer.innerHTML=`<a href="credits.html">${vText('מקורות האיורים ורישיונות','Illustration sources and licences')}</a>`;$('home').appendChild(footer);
});

goBackList=function(){if(detailOrigin==='visualLibrary')openVisualLibrary();else if(detailOrigin==='list')openCat(currentCat);else go(detailOrigin);};

const illustratedBowline=CONTENT.knots.items.find(x=>x.id==='bowline');illustratedBowline.lead={he:'יוצר לולאה קבועה בקצה החבל — לתרגול ולקשירה סביב עצם.',en:'Makes a fixed loop at the end of a rope — for practice and tying around an object.'};illustratedBowline.safety=[{he:'הקשר עלול להשתחרר כשהחבל רפוי. ההדרכה הבסיסית הזאת אינה מיועדת לטיפוס, לתליית אדם או לחילוץ.',en:'The knot can shake loose when unloaded. This basic guide is not for climbing, suspending a person or rescue.'}];
